version: '3.8'

services:
  # The API Service
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  # The MongoDB Service
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

# This ensures our database data isn't lost if we stop the container!
volumes:
  mongo_data: